version: '3.3'

services:
  client:
    container_name: herbal_lux_landingpage
    build:
      context: . 
      dockerfile: docker/client/Dockerfile
    command: tail -f /dev/null
    ports:
      - 5001:3000
      # network_mode: host
    restart: always
    env_file:
      - .env
    volumes:
      - ./client:/project
